"$schema" = 'https://starship.rs/config-schema.json'

# Prompt layout
add_newline = true
format = """
$os\
$directory\
$git_branch\
$git_status\
[┝](subtext1)\
$fill\
[┥](subtext1)\
$cmd_duration\
$kubernetes\
$localip\
$line_break\
$character
"""

# Color palette
palette = 'catppuccin_latte'

# Catppuccin Latte color palette
[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

kubernetes_blue = '#326CE5'

# Operating system module
[os]
disabled = false
format = """
[ $symbol ](fg:lavender)\
"""

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = ""
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

# Directory module
[directory]
format = """
[ $path ](fg:teal)\
([ $read_only](fg:peach))\
"""
truncation_length = 3
truncation_symbol = "󰉖 /"
truncate_to_repo = false
read_only = ''

[directory.substitutions]
Desktop = '󱂵 '
Documents = '󱧶 '
Downloads = '󰉍 '
Music = '󱍙 '
Pictures = '󰉏 '
Public = '󱞊 '
Templates = '󰉓 '
Videos = '󱧺 '
Projects = ' '

# Git module
[git_branch]
symbol = ""
format = """
([ $symbol $branch ](fg:flamingo))\
"""

[git_status]
format = """
([$all_status ](fg:maroon))\
([$ahead_behind ](fg:rosewater))\
"""

# Fill module
[fill]
symbol = '━'
style = 'subtext1'

# Command duration module
[cmd_duration]
style = 'fg:230'
format = """
([ 󱎫 $duration](fg:pink))\
"""

# Kubernetes module
[kubernetes]
disabled = false
symbol = ''
style = 'fg:kubernetes_blue'
format = """
([ $symbol](fg:kubernetes_blue)[ $context ](bold $style)[$namespace ](fg:sky))\
"""

[[kubernetes.contexts]]
context_pattern = ".*live.*"
style = 'fg:flamingo'

[[kubernetes.contexts]]
context_pattern = ".*staging.*"
style = 'fg:lavender'

# Local network information
[localip]
ssh_only = false
disabled = false
format = """
([   $localipv4 ](fg:yellow))\
"""

# Package information is not shown.
[package]
disabled = true
